spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: username
    password: password
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.denizbyrk.sffecommerce: DEBUG